"$schema" = "https://raw.githubusercontent.com/JanDeDobbeleer/oh-my-posh/main/themes/schema.json"
version = 2
final_space = true
console_title_template = '{{ .Shell }} in {{ .Folder }}'

[[blocks]]
type = 'prompt'
alignment = 'left'
filter = '.'
newline = true

[[blocks.segments]]
type = 'os'
style = 'plain'
background = 'transparent'
foreground = 'red'
template = '{{ if .WSL }}WSL at {{ end }}{{.Icon}} '

[[blocks.segments]]
type = 'root'
style = 'plain'
background = "transparent"
foreground = "#ffff66"
tempalte = "\uF0E7"

[[blocks.segments]]
type = 'path'
style = 'plain'
background = 'transparent'
foreground = '#Ff007f'
template = '{{ .Path }} '

[blocks.segments.properties]
style = 'folder'

[[blocks.segments]]
type = 'git'
style = 'plain'
background = 'transparent'
foreground = 'yellow'
foreground_templates = [
  "{{ if or (.Working.Changed) (.Staging.Changed) }}#ffeb95{{ end }}",
  "{{ if and (gt .Ahead 0) (gt .Behind 0) }}#c5e478{{ end }}",
  "{{ if gt .Ahead 0 }}#C792EA{{ end }}",
  "{{ if gt .Behind 0 }}#C792EA{{ end }}",
]
template = " {{ .UpstreamIcon }}{{ .HEAD }}{{if .BranchStatus }} {{ .BranchStatus }}{{ end }}{{ if .Working.Changed }} \uf044 {{ .Working.String }}{{ end }}{{ if and (.Working.Changed) (.Staging.Changed) }} |{{ end }}{{ if .Staging.Changed }} \uf046 {{ .Staging.String }}{{ end }}{{ if gt .StashCount 0 }} \ueb4b {{ .StashCount }}{{ end }}{{ if gt .Behind 0 }}⇣{{ end }}{{ if gt .Ahead 0 }}⇡{{ end }} "

[blocks.segments.properties]
branch_icon = "\ue725 "
fetch_status = true
fetch_upstream_icon = true

[[blocks.segments]]
type = 'text'
style = 'plain'
background = 'transparent'
foreground_templates = [
  "{{if gt .Code 0}}red{{end}}",
  "{{if eq .Code 0}}magenta{{end}}",
]
template = '❯'

[[blocks]]
type = 'rprompt'
overflow = 'hidden'

[[blocks.segments]]
type = 'executiontime'
style = 'plain'
foreground = 'yellow'
background = 'transparent'
template = '{{ .FormattedMs }} '

[blocks.segments.properties]
threshold = 5000

[[blocks.segments]]
type = 'python'
style = 'plain'
background = 'transparent'
foreground = '#FFDE57'
template = " \ue235 {{ if .Error }}{{ .Error }}{{ else }}{{ .Full }}{{ end }} "

[blocks.segments.properties]
fetch_version = false
display_mode = 'context'

[[blocks.segments]]
type = 'cmake'
style = 'plain'
foreground = '#1E9748'
background = 'transparent'
template = " \ue61e \ue61d {{ if .Error }}{{ .Error }}{{ else }}{{ .Full }}{{ end }} "

[[blocks.segments]]
type = 'node'
style = 'plain'
foreground = '#6CA35E'
template = " \ue718 {{ if .PackageManagerIcon }}{{ .PackageManagerIcon }} {{ end }}{{ .Full }} "

[blocks.segments.properties]
fetch_package_manager = true
npm_icon = "<#cc3a3a>\ue71e</>"
yarn_icon = "<#348cba>\ue6a7</>"

[[blocks.segments]]
type = 'java'
style = 'plain'
foreground = '#DF5700'
template = " \ue738 {{ if .Error }}{{ .Error }}{{ else }}{{ .Full }}{{ end }} "

[[blocks.segments]]
type = 'lua'
style = 'plain'
foreground = '#0073E6'
template = " \ue620 {{ if .Error }}{{ .Error }}{{ else }}{{ .Full }}{{ end }} "

[[blocks.segments]]
type = 'go'
style = 'plain'
foreground = '#7FD5EA'
template = " \ue627 {{ if .Error }}{{ .Error }}{{ else }}{{ .Full }}{{ end }} "

[[blocks.segments]]
type = 'session'
style = 'plain'
foreground = 'cyan'
background = 'transparent'
template = '{{ if .SSHSession }} {{ end }}{{ .UserName }}@{{ .HostName }}'

[transient_prompt]
background = 'transparent'
foreground_templates = [
  "{{if gt .Code 0}}red{{end}}",
  "{{if eq .Code 0}}magenta{{end}}",
]
template = '❯ '

[secondary_prompt]
background = 'transparent'
foreground = 'magenta'
template = '❯❯ '
